name: Commit CI/CD

on: 
  push:
    branches: 
      -master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
          with: 
            node-version: 14.15.1
      - run: npm ci
      - run: npm test
      - run: npm run build