language: node_js

node_js:
  - 'stable'

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest
    
    - uses: actions/checkout@v2
    uses: actions/setup-node@v2
      with: 
        node-version: 14
    run: npm ci
    run: npm run build
    run: npm test


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - 'node_modules'
